### ISSUE TITLE
您好，咨询一下，关于TFC这个模型，您的论文里面用到了它，但我发现它的模型跑出来的结果都比较差。请问您是用他github上的代码跑的吗？

### ISSUE THREAD

**Issue by Lqj-creator** [lanxiang1017/DynamicBadPairMining_ICLR24#2]

**Comment by lanxiang1017** [comment]
Hi Qiujin,

We referred to their codes, but instead of using transformer encoders, we employed 1d-cnn due to computational limitations. This could be a factor regarding performance. However, it is important to note that our goal was not to compare performance across different methods. 

I hope this clarifies. Have a nice weekend :)
